/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicationsIndexRouteImport } from './routes/publications.index'
import { Route as PublicationsIdRouteImport } from './routes/publications.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIdRoute = PublicationsIdRouteImport.update({
  id: '/publications/$id',
  path: '/publications/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/publications/': typeof PublicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/publications': typeof PublicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/publications/': typeof PublicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/publications/$id' | '/publications/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/publications/$id' | '/publications'
  id: '__root__' | '/' | '/login' | '/publications/$id' | '/publications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PublicationsIdRoute: typeof PublicationsIdRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$id': {
      id: '/publications/$id'
      path: '/publications/$id'
      fullPath: '/publications/$id'
      preLoaderRoute: typeof PublicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PublicationsIdRoute: PublicationsIdRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
